//
//  ReportExport.swift
//  FinvestLens — FeatureUI
//
//  Copyright (C) 2026 Christine Tham
//  SPDX-License-Identifier: GPL-3.0-or-later
//

import SwiftUI
import UniformTypeIdentifiers
import FinvestLensReports

/// A single printable row. Carries either one `amount` or, for a comparative
/// statement, one `amounts` value per period column.
struct PrintableRow: Identifiable {
    let id = UUID()
    let label: String
    let amount: Decimal
    var bold = false
    /// Per-column amounts (a `nil` renders blank); overrides `amount` when set.
    var amounts: [Decimal?]?
}

/// A titled group of printable rows, optionally with period column headers.
struct PrintableSection: Identifiable {
    let id = UUID()
    let heading: String
    let rows: [PrintableRow]
    var columns: [String]?
}

/// A clean, VStack-based statement layout for PDF rendering (avoids List/Table
/// which virtualise and don't render via ImageRenderer).
struct PrintableStatement: View {
    let title: String
    let subtitle: String
    let code: String
    let sections: [PrintableSection]

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            VStack(alignment: .leading, spacing: 2) {
                Text(title).font(.title2.bold())
                Text(subtitle).font(.subheadline).foregroundStyle(.secondary)
            }
            ForEach(sections) { section in
                if let columns = section.columns {
                    comparativeSection(section, columns: columns)
                } else {
                    VStack(alignment: .leading, spacing: 4) {
                        Text(section.heading).font(.headline)
                        ForEach(section.rows) { row in
                            HStack {
                                Text(row.label).fontWeight(row.bold ? .bold : .regular)
                                Spacer()
                                Text(AmountFormat.string(row.amount, code: code))
                                    .fontWeight(row.bold ? .bold : .regular)
                            }
                        }
                    }
                }
            }
            Text("Generated by FinvestLens").font(.caption2).foregroundStyle(.secondary)
        }
        .foregroundStyle(.black)
    }

    private func comparativeSection(_ section: PrintableSection, columns: [String]) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(section.heading).font(.headline)
            Grid(alignment: .leading, horizontalSpacing: 16, verticalSpacing: 3) {
                GridRow {
                    Text("")
                    ForEach(Array(columns.enumerated()), id: \.offset) { _, header in
                        Text(header).font(.caption).foregroundStyle(.secondary)
                            .gridColumnAlignment(.trailing)
                    }
                }
                ForEach(section.rows) { row in
                    GridRow {
                        Text(row.label).fontWeight(row.bold ? .bold : .regular)
                        ForEach(Array((row.amounts ?? []).enumerated()), id: \.offset) { _, amount in
                            Text(amount.map { AmountFormat.string($0, code: code) } ?? "")
                                .fontWeight(row.bold ? .bold : .regular)
                                .gridColumnAlignment(.trailing)
                        }
                    }
                }
            }
        }
    }
}

/// A PDF document produced from a rendered report, for `fileExporter`
/// (`FR-RPT`, print/PDF).
struct PDFReportDocument: FileDocument {
    static var readableContentTypes: [UTType] { [.pdf] }

    var data: Data
    init(data: Data) { self.data = data }
    init(configuration: ReadConfiguration) throws {
        data = configuration.file.regularFileContents ?? Data()
    }
    func fileWrapper(configuration: WriteConfiguration) throws -> FileWrapper {
        FileWrapper(regularFileWithContents: data)
    }
}

/// Renders a SwiftUI view to single-page PDF data via `ImageRenderer`. Use with
/// a static, VStack-based layout (not `List`/`Table`, which virtualise).
@MainActor
enum ReportExport {
    static func pdf(_ view: some View, scale: CGFloat = 2) -> Data? {
        let renderer = ImageRenderer(content:
            view.padding(24).background(Color.white).frame(width: 560, alignment: .leading))
        renderer.scale = scale

        let pdf = NSMutableData()
        guard let consumer = CGDataConsumer(data: pdf as CFMutableData) else { return nil }
        var mediaBox = CGRect(x: 0, y: 0, width: 612, height: 792)
        guard let context = CGContext(consumer: consumer, mediaBox: &mediaBox, nil) else { return nil }

        renderer.render { size, draw in
            var box = CGRect(origin: .zero, size: size)
            let info = [kCGPDFContextMediaBox as String:
                        CFDataCreate(nil, withUnsafeBytes(of: &box) { $0.bindMemory(to: UInt8.self).baseAddress },
                                     MemoryLayout<CGRect>.size) as Any] as CFDictionary
            context.beginPDFPage(info)
            draw(context)
            context.endPDFPage()
        }
        context.closePDF()
        return pdf as Data
    }
}

// MARK: - PDF toolbar for interactive reports

/// Adds a "PDF" toolbar button to an interactive report view (`FR-RPT-05`).
/// The report keeps its live view; the button builds a printable
/// ``ReportDocument`` from the current data and exports it. `makeDocument`
/// returns `nil` when there is nothing to print (no account chosen, no data).
struct ReportPDFToolbar: ViewModifier {
    let title: String
    let makeDocument: () -> ReportDocument?
    @State private var exporting = false
    @State private var document: PDFReportDocument?

    func body(content: Content) -> some View {
        content
            .toolbar {
                ToolbarItem {
                    Button("PDF", systemImage: "arrow.up.doc") {
                        guard let doc = makeDocument(),
                              let data = ReportExport.pdf(doc.printable) else { return }
                        document = PDFReportDocument(data: data)
                        exporting = true
                    }
                    .help("Export this report as a PDF")
                }
            }
            .fileExporter(isPresented: $exporting, document: document,
                          contentType: .pdf, defaultFilename: title) { _ in }
    }
}

extension View {
    /// Attaches a PDF-export toolbar button that renders `document()` on demand.
    func reportPDFToolbar(title: String,
                          document: @escaping () -> ReportDocument?) -> some View {
        modifier(ReportPDFToolbar(title: title, makeDocument: document))
    }
}
