//
//  BuildInfo.swift
//  finvestlens
//
//  GENERATED by scripts/stamp_build_info.sh — do not edit by hand.
//
//  Copyright (C) 2026 Christine Tham
//  SPDX-License-Identifier: GPL-3.0-or-later
//

import Foundation

/// Build metadata shown on the splash screen.
enum BuildInfo {
    /// Marketing version (matches MARKETING_VERSION in the project).
    static let version = "1.0"
    /// Short git commit the build was cut from.
    static let commit = "e1c742f"
    /// Human-readable build date.
    static let buildDate = "13 July 2026"

    /// e.g. "Version 1.0 (e1c742f)".
    static var versionString: String { "Version \(version) (\(commit))" }
}
