#!/bin/bash
#
#  stamp_build_info.sh — regenerate finvestlens/BuildInfo.swift
#
#  Bakes the marketing version, current git commit and build date into a Swift
#  source file the splash screen reads. Run before a release build (or wire it
#  up as an Xcode "Run Script" build phase). The generated file is committed so
#  plain `xcodebuild` also works.
#
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION="1.0"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
DATE="$(date '+%-d %B %Y')"
OUT="finvestlens/BuildInfo.swift"

cat > "$OUT" <<SWIFT
//
//  BuildInfo.swift
//  finvestlens
//
//  GENERATED by scripts/stamp_build_info.sh — do not edit by hand.
//
//  Copyright (C) 2026 Christine Tham
//  SPDX-License-Identifier: GPL-3.0-or-later
//

import Foundation

/// Build metadata shown on the splash screen.
enum BuildInfo {
    /// Marketing version (matches MARKETING_VERSION in the project).
    static let version = "${VERSION}"
    /// Short git commit the build was cut from.
    static let commit = "${COMMIT}"
    /// Human-readable build date.
    static let buildDate = "${DATE}"

    /// e.g. "Version 1.0 (${COMMIT})".
    static var versionString: String { "Version \\(version) (\\(commit))" }
}
SWIFT

echo "Wrote $OUT — Version $VERSION ($COMMIT), $DATE"
